import type { Partner, Offer } from "./types"
import { mockSupabase as supabase } from "./mock-db"

export async function getPartnerById(id: string): Promise<Partner | null> {
  try {
    const { data, error } = await supabase.from("partners").select("*").eq("id", id).single()

    if (error || !data) {
      return partners.find((p) => p.id === id) || null
    }

    return data as Partner
  } catch (err) {
    console.error("Error fetching partner from Supabase:", err)
    return partners.find((p) => p.id === id) || null
  }
}

export const partners: Partner[] = [
  {
    id: "lighthouse",
    name: "Lighthouse Marina Resort",
    logo: "/images/subic-sailing-hero.jpg",
    image: "/luxury-resort-suite-ocean-view-sunset.jpg",
    category: "hotels",
    description:
      "Premier waterfront resort with stunning views of Subic Bay. Home of the Saturday Afternoon Gentlemen Sailors.",
    discount: 15,
    eliteDiscount: 25,
    offers: ["Aqua Veranda Suite - 25% Off Elite", "Free Room Night for Elite Members", "Sunset Dining Experience"],
    featured: true,
  },
  {
    id: "labanca",
    name: "La Banca Cruises",
    logo: "/images/la-banca-cruises-logo.png",
    image: "/luxury-yacht-cruise-sunset-subic-bay.jpg",
    category: "water-sports",
    description: "Luxury yacht cruises around Subic Bay. Perfect for sunset tours and special occasions.",
    discount: 15,
    eliteDiscount: 25,
    offers: ["FREE 3-Hour Cruise (Elite)", "Sunset Champagne Tour", "Private Island Hopping"],
    featured: true,
  },
  {
    id: "zoobic",
    name: "Zoobic Safari",
    logo: "/images/zoobic-safari-logo.jpeg",
    image: "/tiger-safari-night-dark-dramatic.jpg",
    category: "activities",
    description: "Experience wildlife up close with thrilling safari adventures and animal encounters.",
    discount: 15,
    eliteDiscount: 25,
    offers: ["Priority Access - Skip the Line", "Night Safari Experience", "Tiger Feeding Adventure"],
    featured: true,
  },
  {
    id: "treetop",
    name: "Tree Top Adventure",
    logo: "/images/tree-top-adventure-logo.jpeg",
    image: "/zipline-forest-canopy-adventure-green.jpg",
    category: "activities",
    description: "Nature camp with ziplines, rope courses, and eco-adventures in the Subic forest.",
    discount: 10,
    eliteDiscount: 20,
    offers: ["Canopy Tour Package", "Superman Zipline", "Team Building Activities"],
  },
  {
    id: "funtastic",
    name: "Funtastic Park",
    logo: "/images/funtastic-park-logo.jpeg",
    image: "/images/funtastic-park-logo.jpeg",
    category: "activities",
    description: "Family-friendly amusement park with rides, attractions, and entertainment for all ages.",
    discount: 10,
    eliteDiscount: 20,
    offers: ["All-Day Pass Discount", "Family Bundle", "VIP Fast Pass"],
  },
  {
    id: "networx",
    name: "Networx Jetsports",
    logo: "/images/king-of-watersports.jpg",
    image: "/jet-ski-ocean-watersports-blue-sky.jpg",
    category: "water-sports",
    description: "King of watersports in Subic Bay. Jet skis, banana boats, and aquatic adventures.",
    discount: 15,
    eliteDiscount: 25,
    offers: ["Jet Ski Rental Package", "Banana Boat Group Rate", "Parasailing Adventure"],
  },
  {
    id: "icc",
    name: "ICC Zambales",
    logo: "/images/icc-zambales-logo.png",
    image: "/subic-bay-aerial-view-blue-ocean-tropical.jpg",
    category: "services",
    description: "Local community organization supporting sustainable tourism in Zambales.",
    discount: 10,
    eliteDiscount: 15,
    offers: ["Community Tours", "Local Guide Services", "Cultural Experiences"],
  },
  {
    id: "standard-insurance",
    name: "Standard Insurance",
    logo: "/images/standard-insurance-logo.png",
    image: "/images/standard-insurance-logo.png",
    category: "services",
    description: "Comprehensive travel insurance coverage for all Subic.Life members.",
    discount: 0,
    eliteDiscount: 0,
    offers: ["Personal Accident Coverage", "Medical Evacuation", "Trip Cancellation Protection"],
  },
  {
    id: "assist-america",
    name: "Assist America",
    logo: "/images/assist-america-logo.jpg",
    image: "/images/assist-america-logo.jpg",
    category: "services",
    description: "Global emergency assistance services for travelers.",
    discount: 0,
    eliteDiscount: 0,
    offers: ["24/7 Emergency Hotline", "Medical Referrals", "Emergency Evacuation"],
  },
]

export const featuredOffers: Offer[] = [
  {
    id: "offer-1",
    partnerId: "lighthouse",
    partnerName: "Lighthouse Marina Resort",
    title: "Aqua Veranda Suite",
    description: "25% Off for Elite Members",
    image: "/luxury-resort-suite-ocean-view-sunset.jpg",
    discount: 25,
    originalPrice: 8000,
    discountedPrice: 6000,
    category: "hotels",
  },
  {
    id: "offer-2",
    partnerId: "labanca",
    partnerName: "La Banca Cruises",
    title: "3-Hour Yacht Cruise",
    description: "FREE for Elite Members",
    image: "/luxury-yacht-cruise-sunset-subic-bay.jpg",
    discount: 100,
    isEliteExclusive: true,
    originalPrice: 15000,
    discountedPrice: 0,
    category: "water-sports",
  },
  {
    id: "offer-3",
    partnerId: "zoobic",
    partnerName: "Zoobic Safari",
    title: "Night Safari Experience",
    description: "Priority Access + 25% Off",
    image: "/tiger-safari-night-dark-dramatic.jpg",
    discount: 25,
    originalPrice: 1200,
    discountedPrice: 900,
    category: "activities",
  },
  {
    id: "offer-4",
    partnerId: "treetop",
    partnerName: "Tree Top Adventure",
    title: "Canopy Tour Package",
    description: "20% Off Adventure Bundle",
    image: "/zipline-forest-canopy-adventure-green.jpg",
    discount: 20,
    originalPrice: 2500,
    discountedPrice: 2000,
    category: "activities",
  },
  {
    id: "offer-5",
    partnerId: "networx",
    partnerName: "Networx Jetsports",
    title: "Jet Ski Adventure",
    description: "25% Off Water Sports",
    image: "/jet-ski-ocean-watersports-blue-sky.jpg",
    discount: 25,
    originalPrice: 3000,
    discountedPrice: 2250,
    category: "water-sports",
  },
]

export const allOffers: Offer[] = [
  // Lighthouse Marina Resort
  {
    id: "offer-lighthouse-1",
    partnerId: "lighthouse",
    partnerName: "Lighthouse Marina Resort",
    title: "Aqua Veranda Suite",
    description: "25% Off for Elite Members",
    image: "/luxury-resort-suite-ocean-view-sunset.jpg",
    discount: 25,
    isEliteExclusive: true,
    originalPrice: 8000,
    discountedPrice: 6000,
    category: "hotels",
  },
  {
    id: "offer-lighthouse-2",
    partnerId: "lighthouse",
    partnerName: "Lighthouse Marina Resort",
    title: "Sunset Dining Experience",
    description: "Gourmet dinner by the bay",
    image: "/luxury-resort-suite-ocean-view-sunset.jpg",
    discount: 20,
    originalPrice: 3500,
    discountedPrice: 2800,
    category: "hotels",
  },
  // La Banca Cruises
  {
    id: "offer-labanca-1",
    partnerId: "labanca",
    partnerName: "La Banca Cruises",
    title: "FREE 3-Hour Cruise",
    description: "Exclusive yacht experience for Elite",
    image: "/luxury-yacht-cruise-sunset-subic-bay.jpg",
    discount: 100,
    isEliteExclusive: true,
    originalPrice: 15000,
    discountedPrice: 0,
    category: "water-sports",
  },
  {
    id: "offer-labanca-2",
    partnerId: "labanca",
    partnerName: "La Banca Cruises",
    title: "Sunset Champagne Tour",
    description: "Romantic cruise with champagne",
    image: "/luxury-yacht-cruise-sunset-subic-bay.jpg",
    discount: 20,
    originalPrice: 12000,
    discountedPrice: 9600,
    category: "water-sports",
  },
  // Zoobic Safari
  {
    id: "offer-zoobic-1",
    partnerId: "zoobic",
    partnerName: "Zoobic Safari",
    title: "Night Safari Experience",
    description: "Thrilling wildlife adventure at night",
    image: "/tiger-safari-night-dark-dramatic.jpg",
    discount: 25,
    isEliteExclusive: true,
    originalPrice: 1200,
    discountedPrice: 900,
    category: "activities",
  },
  {
    id: "offer-zoobic-2",
    partnerId: "zoobic",
    partnerName: "Zoobic Safari",
    title: "Tiger Feeding Adventure",
    description: "Close encounter with majestic tigers",
    image: "/tiger-safari-night-dark-dramatic.jpg",
    discount: 20,
    originalPrice: 1500,
    discountedPrice: 1200,
    category: "activities",
  },
  // Tree Top Adventure
  {
    id: "offer-treetop-1",
    partnerId: "treetop",
    partnerName: "Tree Top Adventure",
    title: "Canopy Tour Package",
    description: "Zipline through the forest canopy",
    image: "/zipline-forest-canopy-adventure-green.jpg",
    discount: 20,
    originalPrice: 2500,
    discountedPrice: 2000,
    category: "activities",
  },
  {
    id: "offer-treetop-2",
    partnerId: "treetop",
    partnerName: "Tree Top Adventure",
    title: "Superman Zipline",
    description: "Fly like a superhero above the trees",
    image: "/zipline-forest-canopy-adventure-green.jpg",
    discount: 20,
    originalPrice: 1800,
    discountedPrice: 1440,
    category: "activities",
  },
  // Funtastic Park
  {
    id: "offer-funtastic-1",
    partnerId: "funtastic",
    partnerName: "Funtastic Park",
    title: "All-Day Pass Discount",
    description: "Unlimited fun for the whole family",
    image: "/images/funtastic-park-logo.jpeg",
    discount: 20,
    originalPrice: 1200,
    discountedPrice: 960,
    category: "activities",
  },
  {
    id: "offer-funtastic-2",
    partnerId: "funtastic",
    partnerName: "Funtastic Park",
    title: "VIP Fast Pass",
    description: "Skip the lines for all attractions",
    image: "/images/funtastic-park-logo.jpeg",
    discount: 20,
    isEliteExclusive: true,
    originalPrice: 2000,
    discountedPrice: 1600,
    category: "activities",
  },
  // Networx Jetsports
  {
    id: "offer-networx-1",
    partnerId: "networx",
    partnerName: "Networx Jetsports",
    title: "Jet Ski Rental Package",
    description: "High-speed fun on the water",
    image: "/jet-ski-ocean-watersports-blue-sky.jpg",
    discount: 25,
    originalPrice: 3000,
    discountedPrice: 2250,
    category: "water-sports",
  },
  {
    id: "offer-networx-2",
    partnerId: "networx",
    partnerName: "Networx Jetsports",
    title: "Parasailing Adventure",
    description: "Soar high above Subic Bay",
    image: "/jet-ski-ocean-watersports-blue-sky.jpg",
    discount: 20,
    isEliteExclusive: true,
    originalPrice: 2500,
    discountedPrice: 2000,
    category: "water-sports",
  },
  // ICC Zambales
  {
    id: "offer-icc-1",
    partnerId: "icc",
    partnerName: "ICC Zambales",
    title: "Community Tours",
    description: "Explore the local culture and scenery",
    image: "/subic-bay-aerial-view-blue-ocean-tropical.jpg",
    discount: 20,
    originalPrice: 800,
    discountedPrice: 640,
    category: "services",
  },
  // Standard Insurance
  {
    id: "offer-standard-1",
    partnerId: "standard-insurance",
    partnerName: "Standard Insurance",
    title: "Personal Accident Coverage",
    description: "Stay protected during your adventures",
    image: "/images/standard-insurance-logo.png",
    discount: 0,
    originalPrice: 5000,
    discountedPrice: 5000,
    category: "services",
  },
  // Assist America
  {
    id: "offer-assist-1",
    partnerId: "assist-america",
    partnerName: "Assist America",
    title: "24/7 Emergency Hotline",
    description: "Global emergency assistance anytime",
    image: "/images/assist-america-logo.jpg",
    discount: 0,
    originalPrice: 3000,
    discountedPrice: 3000,
    category: "services",
  },
]
